apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app-project
  replicas: 2
  template:
    metadata:
      labels:
        app: app-project
    spec:
      containers: 
        - name: app-container
          image: "sameeraja/sam-finalimage"
          ports:
           - containerPort: 8080
           
           
                   
