- name: preparing initial setup
  hosts: app
  become: yes
 
  tasks:
   - name: installing common tools
     yum:
       name:
          - unzip
          - wget
          - vim
       state: present
   - name: installing git
     yum:
        name: git
        state: present
   - name: installing java
     package:
        name: java-1.8.0
        state: present
   - name: Add jenkins repo 
     get_url:
       url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
       dest: /etc/yum.repos.d/jenkins.repo
   - name: Key for rpm
     shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
   - name: Install Jenkins package.
     yum:
       name: jenkins
       state: present
   - name: Enable jenkins
     service:
       name: jenkins
       enabled: yes
   - name: Start jenkins
     service:
       name: jenkins
       state: started
   - name: Install docker
     yum:
       name: docker
       state: present
   - name: Start docker service
     service:
       name: docker 
       state: started
       enabled: yes
   - name: Add docker group
     shell: groupadd centos
     ignore_errors: true
   - name: Add dockeradmin user to docker group
     user:
       name: centos
       groups: docker
       append: yes
   - name: Install maven
     yum:
       name: maven
       state: present
   - name: Install tomcat
     get_url: 
       url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz
       dest: /home/centos       
     become: no
   - name: Extract Archive
     unarchive:
       src: /home/centos/apache-tomcat-7.0.94.tar.gz
       dest: /home/centos
       remote_src: yes
     become: no
   - name: Start tomcat
     shell: /home/centos/apache-tomcat-7.0.94/bin/startup.sh
   - name: Install nexus
     get_url:
      url: https://download.sonatype.com/nexus/oss/nexus-2.14.18-01-bundle.tar.gz
      dest: /home/centos
     become: no
   - name: Extract nexus
     unarchive: 
       src: /home/centos/nexus-2.14.18-01-bundle.tar.gz
       dest: /home/centos
       remote_src: yes
     become: no
   - name: Start Nexus
     shell: /home/centos/nexus-2.14.18-01/bin/nexus start
     become: no
   - name: Install Sonarqube
     get_url:
      url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.7.zip
      dest: /home/centos
     become: no
   - name: Unzip Sonarqube
     unarchive:
       src: /home/centos/sonarqube-6.7.7.zip
       dest: /home/centos
       remote_src: yes
     become: no
   - name: Start Sonarqube
     shell: /home/centos/sonarqube-6.7.7/bin/linux-x86-64/sonar.sh start
     become: no
       
       
          
 
        
