- name: kops setup
  hosts: kops
  tasks:
   - name: Installing common components
     yum:
       name:
          - unzip
          - wget
          - vim
       state: present
     become: yes
   - name: Install Kops on ec2
     shell: |
       curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
       chmod +x kops-linux-amd64
       sudo mv kops-linux-amd64 /usr/local/bin/kops
   - name: Install kubectl
     shell: |
       curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
       chmod +x ./kubectl
       sudo mv ./kubectl /usr/local/bin/kubectl
   - name: installing aws-cli
     shell: |
       sudo yum install python -y
       curl -O https://bootstrap.pypa.io/get-pip.py
       python get-pip.py
       sudo yum install awscli -y  || pip install awscli
   - name: Creating s3 bucket
     shell: aws s3 mb s3://sameera.club.k8s --region us-east-2
     ignore_errors: true
   - name: creating cluster state - 1
     shell: echo | ssh-keygen -P ''
     ignore_errors: yes
   - name: creating cluster state - 2
     shell: | 
     export KOPS_CLUSTER_NAME:sameera.club
     export KOPS_STATE_STORE=s3://sameera.club.k8s 
   - name: Creating cluster definition
     shell: |
       (kops validate cluster --state=s3://sameera.club.k8s --name: sameera.club) || (kops create cluster --state=s3://sameera.club.k8s --node-count=2 --master-size=t2.micro --node-size=t2.micro --zones=us-east-2a,us-east-2b --name= sameera.club --dns private --master-count 1 --yes)
      
        
