- name: kops setup
  hosts: kops
  tasks:
   - name: Install Kops on ec2
     shell: |
       curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
       chmod +x kops-linux-amd64
       sudo mv kops-linux-amd64 /usr/local/bin/kops
   - name: Install kubectl
     shell: |
       curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
       chmod +x ./kubectl
       sudo mv ./kubectl /usr/local/bin/kubectl
   - name: Installing Aws cli
     shell: |
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip awscliv2.zip
         sudo ./aws/install
   - name: Creating s3 bucket
     shell: aws s3 mb s3://sameera.club.k8s --region us-east-2
   - name: Creating cluster definition
     shell: |
       kops create cluster --state=s3://sameera.club.k8s --node-count=2 --master-size=t2.micro --node-size=t2.micro --zones=us-east-2a,us-east-2b --name=sameera.club --dns private --master-count 1
       kops update cluster --yes
       kops validate cluster
